default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: false
  pool: 15
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: profile_development

production:
  <<: *default
  database: profile_production
